name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 18.157.180.48 >> ~/.ssh/known_hosts

      - name: Deploy code
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.157.180.48 << 'EOF'
            # Ensure the deployment directory exists
            mkdir -p /home/ubuntu/DevProject

            # Change to the deployment directory
            cd /home/ubuntu/DevProject || exit

            # Ensure the directory is empty before cloning (optional)
            rm -rf /home/ubuntu/DevProject/*

            # Clone the repository or update if it already exists
            if [ ! -d ".git" ]; then
              git clone https://github.com/karl-nohra1/DevopsProject.git /home/ubuntu/DevProject
            else
              git pull
            fi

            # Optionally, add build commands or other deployment steps here
            # e.g., npm install && npm run build
          EOF
